server:
  port: 8082

spring:

  application:
    name: TODOList

  datasource:
    url: jdbc:mysql://localhost:3306/TODOList?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true